## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [1]:
#1
import numpy as np
matrix1 = np.zeros((10, 10))
matrix1[0, :] = 1
matrix1[-1, :] = 1
matrix1[:, 0] = 1
matrix1[:, -1] = 1
print(matrix1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Create a 5*5 matrix with each row being 0 to 4

In [2]:
#2
matrix2 = np.tile(np.arange(5), (5, 1))
print(matrix2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [3]:
#3
matrix3 = np.zeros((8, 8), dtype=int)
matrix3[1::2, ::2] = 1
# matrix3[::2, 1::2] = 1
print(matrix3)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [4]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odds = arr[arr % 2 == 1]
print(odds)

[1 3 5 7 9]


5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [5]:
#5
random_matrix = np.random.normal(4, 3, (5, 5))
mean = random_matrix.mean()
std = random_matrix.std()
normalized_matrix = (random_matrix - mean) / std
print(normalized_matrix)

[[-0.12027822 -2.72656637 -0.26229572  0.15769054 -0.31014909]
 [ 0.35512149  0.1894333  -0.08687529  0.43305537 -0.89691363]
 [-1.21525122  0.35992031  1.13140075 -0.18720428 -0.59513536]
 [-0.87191245  0.99607706 -0.36426584  0.37978608 -0.99132493]
 [ 2.68635816  0.4935272   0.71615245 -0.54980306  1.27945272]]


6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [6]:
# Output the X, Y, R, and T values in a clear format

# Given data for X and Y (Cartesian coordinates)
X = np.array([0.48660129, 0.64067014, 0.93301119, 0.55328471, 0.2628861,  
              0.18080466, 0.28289352, 0.99464788, 0.42403243, 0.49718628])
Y = np.array([0.46385448, 0.97130751, 0.4472571, 0.78994386, 0.56000864, 
              0.77150557, 0.6863419, 0.88128735, 0.5663552, 0.31280192])

# Calculate R and T (Polar coordinates)
R = np.sqrt(X**2 + Y**2)  # Radius
T = np.arctan2(Y, X)      # Theta (in radians)

# Display the values of X, Y, R, and T
import pandas as pd

data = {
    "X": X,
    "Y": Y,
    "R (Radius)": R,
    "T (Theta in Radians)": T
}

df = pd.DataFrame(data)
print(df)

          X         Y  R (Radius)  T (Theta in Radians)
0  0.486601  0.463854    0.672266              0.761470
1  0.640670  0.971308    1.163571              0.987705
2  0.933011  0.447257    1.034673              0.447007
3  0.553285  0.789944    0.964435              0.959795
4  0.262886  0.560009    0.618643              1.131901
5  0.180805  0.771506    0.792408              1.340598
6  0.282894  0.686342    0.742357              1.179838
7  0.994648  0.881287    1.328906              0.725043
8  0.424032  0.566355    0.707504              0.928125
9  0.497186  0.312802    0.587400              0.561574


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [7]:
#7
vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) * 4 - 3)
new_vector[::4] = vector
print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [8]:
#8
print(0 * np.nan,

np.nan == np.nan

,np.inf > np.nan

,np.nan - np.nan

,np.nan in set([np.nan])

,0.3 == 3 * 0.1 )

nan False False nan True False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [9]:
print(np.array(0) / np.array(0),

np.array(0) // np.array(0),

np.array([np.nan]).astype(int).astype(float))

nan 0 [-2.14748365e+09]


C:\Users\83876\AppData\Local\Temp\ipykernel_4376\2389941569.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0),
C:\Users\83876\AppData\Local\Temp\ipykernel_4376\2389941569.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0),
C:\Users\83876\AppData\Local\Temp\ipykernel_4376\2389941569.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float))
